import axios from 'axios';

interface PullRequest {
  number: number;
  html_url: string;
  title: string;
}

/**
 * Create a GitHub pull request using the GitHub API
 */
export async function createPullRequest(
  branchName: string,
  title: string,
  body: string,
  draft: boolean = true
): Promise<PullRequest> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error('GITHUB_TOKEN environment variable is required');
  }

  const repository = process.env.GITHUB_REPOSITORY;
  if (!repository) {
    throw new Error('GITHUB_REPOSITORY environment variable is required');
  }

  const [owner, repo] = repository.split('/');
  const apiUrl = `https://api.github.com/repos/${owner}/${repo}/pulls`;

  try {
    console.log(`Creating pull request for ${branchName}...`);

    const response = await axios.post(
      apiUrl,
      {
        title,
        head: branchName,
        base: 'main',
        body,
        draft,
      },
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github.v3+json',
        },
      }
    );

    const pr = response.data;
    console.log(`✓ Created pull request #${pr.number}: ${pr.html_url}`);

    return {
      number: pr.number,
      html_url: pr.html_url,
      title: pr.title,
    };
  } catch (error: any) {
    if (error.response?.status === 422) {
      console.error('Pull request already exists or validation failed');
      console.error(error.response.data);
    } else {
      console.error('Error creating pull request:', error.message);
    }
    throw error;
  }
}

/**
 * Generate pull request body
 */
export function generatePRBody(
  week: number,
  year: number,
  stats: {
    totalItems: number;
    categoryCounts: Record<string, number>;
    sources: string[];
  }
): string {
  const categoriesList = Object.entries(stats.categoryCounts)
    .filter(([_, count]) => count > 0)
    .map(([category, count]) => `- ${category}: ${count}`)
    .join('\n');

  return `## DevOps Weekly Digest - Week ${week}, ${year}

### Summary

This PR contains the automated weekly digest of DevOps news and updates.

### Statistics

- **Total items**: ${stats.totalItems}
- **Unique sources**: ${stats.sources.length}

### By Category

${categoriesList}

### Test Plan

- [ ] Review markdown formatting
- [ ] Verify all links are valid
- [ ] Check content quality
- [ ] Ensure no duplicate items

---

*This PR was automatically generated by the DevOps Daily digest script.*
`;
}
